/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Helper.DialogHelper;
import Helper.ShareHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Quang
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    public void init() {
        setIconImage(ShareHelper.appIcon());

        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
        }).start();

        this.openWelcome();
        this.openLogin();
    }

    public void openLogin() {
        LogIn login = new LogIn(this, true);

        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        login.setVisible(true);
    }

    public void openWelcome() {
        Welcome welcome = new Welcome(this, true);

        welcome.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        welcome.setVisible(true);
    }

    public void logOff() {
        ShareHelper.logoff();
//        this.dispose();

        LogIn login = new LogIn(this, true);

        login.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        login.setVisible(true);
    }

    public void exit() {
        if (DialogHelper.confirm(this, "Bạn có chắc muốn kết thúc không?")) {
            System.exit(0);
        }
    }

    public void openThongKe(int index) {
        if (ShareHelper.authenticated()) {
            new Statistics(this, true).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập!");
        }
    }

    public void openNhanVien() {
        if (ShareHelper.authenticated()) {
            new Employee(this, true).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void openKhoaHoc() {
        if (ShareHelper.authenticated()) {
            new Course(this,true).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void openChuyenDe() {
        if (ShareHelper.authenticated()) {
            new Thematic(this, true).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void openNguoiHoc() {
        if (ShareHelper.authenticated()) {
            new Learner(this, true).setVisible(true);
        } else {
            DialogHelper.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void openAbout() {
        new Introduction(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblDangXuat = new javax.swing.JLabel();
        lblKetThuc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lblChuyenDe = new javax.swing.JLabel();
        lblNguoiHoc = new javax.swing.JLabel();
        lblKhoahoc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        lblHuongDan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDangNhap = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        sep1 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniQLNguoiHoc = new javax.swing.JMenuItem();
        mniQLChuyenDe = new javax.swing.JMenuItem();
        mniQLKhoaHoc = new javax.swing.JMenuItem();
        mniQLNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniTKNguoiHoc = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniTKBangDiem = new javax.swing.JMenuItem();
        mniTKKhoaHoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniTKDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setBackground(new java.awt.Color(204, 204, 204));

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        lblDangXuat.setBackground(new java.awt.Color(0, 0, 0));
        lblDangXuat.setForeground(new java.awt.Color(0, 0, 0));
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Log out.png"))); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.setToolTipText("");
        lblDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIconTextGap(5);
        lblDangXuat.setMaximumSize(new java.awt.Dimension(70, 53));
        lblDangXuat.setName(""); // NOI18N
        lblDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
        });
        jToolBar1.add(lblDangXuat);

        lblKetThuc.setBackground(new java.awt.Color(0, 0, 0));
        lblKetThuc.setForeground(new java.awt.Color(0, 0, 0));
        lblKetThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Stop.png"))); // NOI18N
        lblKetThuc.setText("Kết thúc");
        lblKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblKetThuc.setIconTextGap(5);
        lblKetThuc.setMaximumSize(new java.awt.Dimension(70, 53));
        lblKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKetThucMouseClicked(evt);
            }
        });
        jToolBar1.add(lblKetThuc);
        jToolBar1.add(jSeparator1);

        lblChuyenDe.setBackground(new java.awt.Color(0, 0, 0));
        lblChuyenDe.setForeground(new java.awt.Color(0, 0, 0));
        lblChuyenDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Lists.png"))); // NOI18N
        lblChuyenDe.setText("Chuyên đề");
        lblChuyenDe.setFocusable(false);
        lblChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblChuyenDe.setIconTextGap(5);
        lblChuyenDe.setMaximumSize(new java.awt.Dimension(70, 53));
        lblChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChuyenDeMouseClicked(evt);
            }
        });
        jToolBar1.add(lblChuyenDe);

        lblNguoiHoc.setBackground(new java.awt.Color(0, 0, 0));
        lblNguoiHoc.setForeground(new java.awt.Color(0, 0, 0));
        lblNguoiHoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Conference.png"))); // NOI18N
        lblNguoiHoc.setText("Người học");
        lblNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNguoiHoc.setIconTextGap(5);
        lblNguoiHoc.setMaximumSize(new java.awt.Dimension(70, 53));
        lblNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNguoiHocMouseClicked(evt);
            }
        });
        jToolBar1.add(lblNguoiHoc);

        lblKhoahoc.setBackground(new java.awt.Color(0, 0, 0));
        lblKhoahoc.setForeground(new java.awt.Color(0, 0, 0));
        lblKhoahoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Certificate.png"))); // NOI18N
        lblKhoahoc.setText("Khoá học");
        lblKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblKhoahoc.setIconTextGap(5);
        lblKhoahoc.setMaximumSize(new java.awt.Dimension(70, 53));
        lblKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblKhoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhoahocMouseClicked(evt);
            }
        });
        jToolBar1.add(lblKhoahoc);
        jToolBar1.add(jSeparator2);

        lblHuongDan.setBackground(new java.awt.Color(0, 0, 0));
        lblHuongDan.setForeground(new java.awt.Color(0, 0, 0));
        lblHuongDan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Globe.png"))); // NOI18N
        lblHuongDan.setText("Hướng dẫn");
        lblHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHuongDan.setIconTextGap(5);
        lblHuongDan.setMaximumSize(new java.awt.Dimension(70, 53));
        lblHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuongDanMouseClicked(evt);
            }
        });
        jToolBar1.add(lblHuongDan);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblTrangThai.setForeground(new java.awt.Color(0, 0, 0));
        lblTrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Info.png"))); // NOI18N
        lblTrangThai.setText("Hệ quản lý đào tạo");
        lblTrangThai.setPreferredSize(new java.awt.Dimension(150, 30));

        lblDongHo.setBackground(new java.awt.Color(0, 0, 0));
        lblDongHo.setForeground(new java.awt.Color(0, 0, 0));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Alarm.png"))); // NOI18N
        lblDongHo.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDongHo)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-FPT-Polytechnic- (1).png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        mnuHeThong.setBackground(new java.awt.Color(204, 204, 204));
        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuHeThong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuHeThong.setMaximumSize(new java.awt.Dimension(60, 20));
        mnuHeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThongActionPerformed(evt);
            }
        });

        mniDangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Key.png"))); // NOI18N
        mniDangNhap.setText("Đăng nhập");
        mniDangNhap.setToolTipText("");
        mniDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDangNhapMouseClicked(evt);
            }
        });
        mniDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangNhap);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Log out.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniDangXuatMouseClicked(evt);
            }
        });
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(sep1);

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Refresh.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mnuHeThong.add(mniDoiMatKhau);
        mnuHeThong.add(jSeparator4);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Stop.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniKetThucMouseClicked(evt);
            }
        });
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        jMenuBar1.add(mnuHeThong);

        mnuQuanLy.setBackground(new java.awt.Color(204, 204, 204));
        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuQuanLy.setMaximumSize(new java.awt.Dimension(60, 20));

        mniQLNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Conference.png"))); // NOI18N
        mniQLNguoiHoc.setText("Người học");
        mniQLNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniQLNguoiHocMouseClicked(evt);
            }
        });
        mnuQuanLy.add(mniQLNguoiHoc);

        mniQLChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Lists.png"))); // NOI18N
        mniQLChuyenDe.setText("Chuyên đề");
        mniQLChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniQLChuyenDeMouseClicked(evt);
            }
        });
        mnuQuanLy.add(mniQLChuyenDe);

        mniQLKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Certificate.png"))); // NOI18N
        mniQLKhoaHoc.setText("Khoá học");
        mniQLKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniQLKhoaHocMouseClicked(evt);
            }
        });
        mnuQuanLy.add(mniQLKhoaHoc);

        mniQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/User group.png"))); // NOI18N
        mniQLNhanVien.setText("Nhân viên");
        mniQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniQLNhanVienMouseClicked(evt);
            }
        });
        mnuQuanLy.add(mniQLNhanVien);

        jMenuBar1.add(mnuQuanLy);

        mnuThongKe.setBackground(new java.awt.Color(204, 204, 204));
        mnuThongKe.setText("Thống kê");
        mnuThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuThongKe.setMaximumSize(new java.awt.Dimension(60, 20));

        mniTKNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Clien list.png"))); // NOI18N
        mniTKNguoiHoc.setText("Người học từng năm");
        mnuThongKe.add(mniTKNguoiHoc);
        mnuThongKe.add(jSeparator5);

        mniTKBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Card file.png"))); // NOI18N
        mniTKBangDiem.setText("Bảng điểm khoá...");
        mnuThongKe.add(mniTKBangDiem);

        mniTKKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Bar chart.png"))); // NOI18N
        mniTKKhoaHoc.setText("Điểm từng khoá học");
        mnuThongKe.add(mniTKKhoaHoc);
        mnuThongKe.add(jSeparator6);

        mniTKDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Dollar.png"))); // NOI18N
        mniTKDoanhThu.setText("Doanh thu từng chuyên đề...");
        mnuThongKe.add(mniTKDoanhThu);

        jMenuBar1.add(mnuThongKe);

        mnuTroGiup.setBackground(new java.awt.Color(204, 204, 204));
        mnuTroGiup.setText("Trợ giúp");
        mnuTroGiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuTroGiup.setMaximumSize(new java.awt.Dimension(60, 20));

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Globe.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(jSeparator7);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Hinh/Brick house.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu sản phẩm");
        mniGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniGioiThieuMouseClicked(evt);
            }
        });
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);

        jMenuBar1.add(mnuTroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel9)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThongActionPerformed
    }//GEN-LAST:event_mnuHeThongActionPerformed

    private void mniDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangNhapActionPerformed
        openLogin();
    }//GEN-LAST:event_mniDangNhapActionPerformed

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        logOff();
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKetThucMouseClicked
        exit();
    }//GEN-LAST:event_lblKetThucMouseClicked

    private void lblChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenDeMouseClicked
        openChuyenDe();
    }//GEN-LAST:event_lblChuyenDeMouseClicked

    private void lblNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNguoiHocMouseClicked
        openNguoiHoc();
    }//GEN-LAST:event_lblNguoiHocMouseClicked

    private void lblKhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoahocMouseClicked
        openKhoaHoc();
    }//GEN-LAST:event_lblKhoahocMouseClicked

    private void lblHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMouseClicked
    }//GEN-LAST:event_lblHuongDanMouseClicked

    private void mniDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDangNhapMouseClicked
    }//GEN-LAST:event_mniDangNhapMouseClicked

    private void mniDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniDangXuatMouseClicked
    }//GEN-LAST:event_mniDangXuatMouseClicked

    private void mniKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniKetThucMouseClicked
    }//GEN-LAST:event_mniKetThucMouseClicked

    private void mniQLNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniQLNguoiHocMouseClicked
        openNguoiHoc();
    }//GEN-LAST:event_mniQLNguoiHocMouseClicked

    private void mniQLChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniQLChuyenDeMouseClicked
        openChuyenDe();
    }//GEN-LAST:event_mniQLChuyenDeMouseClicked

    private void mniQLKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniQLKhoaHocMouseClicked
        openKhoaHoc();
    }//GEN-LAST:event_mniQLKhoaHocMouseClicked

    private void mniQLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniQLNhanVienMouseClicked
        openNhanVien();
    }//GEN-LAST:event_mniQLNhanVienMouseClicked

    private void mniGioiThieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniGioiThieuMouseClicked
    }//GEN-LAST:event_mniGioiThieuMouseClicked

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        logOff();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        exit();
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        openAbout();
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblChuyenDe;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblHuongDan;
    private javax.swing.JLabel lblKetThuc;
    private javax.swing.JLabel lblKhoahoc;
    private javax.swing.JLabel lblNguoiHoc;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JMenuItem mniDangNhap;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniQLChuyenDe;
    private javax.swing.JMenuItem mniQLKhoaHoc;
    private javax.swing.JMenuItem mniQLNguoiHoc;
    private javax.swing.JMenuItem mniQLNhanVien;
    private javax.swing.JMenuItem mniTKBangDiem;
    private javax.swing.JMenuItem mniTKDoanhThu;
    private javax.swing.JMenuItem mniTKKhoaHoc;
    private javax.swing.JMenuItem mniTKNguoiHoc;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPopupMenu.Separator sep1;
    // End of variables declaration//GEN-END:variables
}
